// <auto-generated />
using System;
using FMS.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FMS.Models.Common.TebConfigData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccelerationAngularLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccelerationLinearLimit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowInitializeWithBackwardMotion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackwardMaxVelocity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DtHysteresis")
                        .HasColumnType("TEXT");

                    b.Property<string>("DtRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("DynamicObstacleInflationRadius")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForkliftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardMaxVelocity")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalToleranceXY")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalToleranceYaw")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeCostmapObstacles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeDynamicObstacles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinimalObstacleDistance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OscillationRecovery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaveSettings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaticObstacleInflationRadius")
                        .HasColumnType("TEXT");

                    b.Property<string>("TurningMaxVelocity")
                        .HasColumnType("TEXT");

                    b.Property<string>("TurningRadius")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wheelbase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForkliftId")
                        .IsUnique();

                    b.ToTable("TebConfigDatas");
                });

            modelBuilder.Entity("FMS.Models.Main.Forklift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForkliftAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LidarLocAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisionaryAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Forklifts");
                });

            modelBuilder.Entity("FMS.Models.Main.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQueued")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FMS.Models.Main.JobStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobStepLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobStepLocationId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobSteps");
                });

            modelBuilder.Entity("FMS.Models.Main.JobStepType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobStepTypes");
                });

            modelBuilder.Entity("FMS.Models.Main.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionX")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionY")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FMS.Models.Main.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClient")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInstallator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NfcTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FMS.Models.Common.TebConfigData", b =>
                {
                    b.HasOne("FMS.Models.Main.Forklift", null)
                        .WithOne("BackedUpTebConfig")
                        .HasForeignKey("FMS.Models.Common.TebConfigData", "ForkliftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FMS.Models.Main.JobStep", b =>
                {
                    b.HasOne("FMS.Models.Main.Job", null)
                        .WithMany("JobStepsList")
                        .HasForeignKey("JobId");

                    b.HasOne("FMS.Models.Main.Location", "JobStepLocation")
                        .WithMany()
                        .HasForeignKey("JobStepLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMS.Models.Main.JobStepType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobStepLocation");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("FMS.Models.Main.Forklift", b =>
                {
                    b.Navigation("BackedUpTebConfig");
                });

            modelBuilder.Entity("FMS.Models.Main.Job", b =>
                {
                    b.Navigation("JobStepsList");
                });
#pragma warning restore 612, 618
        }
    }
}
